### PR TITLE
Updating getting_started.md: how to disable the logging

### PR DESCRIPTION
**Pull request by boechat107**
An instruction to get ride of logging messages from the driver was added
to `getting_started.md`. A reference to the solution's source was also given.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@boechat107 I'm not sure this topic is *so* important it has to be covered before `Connecting`.

**Comment by michaelklishin** [comment]
@boechat107 thank you for your time attempting to cover this. I think I'll take over this.

**Comment by boechat107** [comment]
Some suggestion? Or is it not important at all?

**Comment by michaelklishin** [comment]
@boechat107 it is useful to cover this (even though it's a Java driver thing) but why on earth would it be covered *before everything else*? It doesn't belong to any of the existing guides, so I'll add a new one and mention it at the end of Getting Started.

**Comment by boechat107** [comment]
OK, I got it.

**Pull request closed without merging**
